version: '3'

services:
  discord_bot:
    build:
      context: .
    restart: always
    command: python main.py
    working_dir: "/project/"
    tty: true
    volumes:
      - ./src:/project
      - ./imgs:/project